import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/instrument-serif/latin-400.css';
import { ITEMS } from './content';
import './assets.css';
import {Bobblehead} from './bobblehead';
import {prepareOfficeMaterials} from './office';
const PROPS=[...ITEMS.map(s=>({id:s.id})),{id:'dwight-bobblehead'},{id:'desk'},{id:'office-room'},{id:'scranton-office'},{id:'scranton-ground-floor'},{id:'scranton-elevator'}];
document.querySelector('#asset-app')!.innerHTML=`<header><a href="/">← Back to desk jelly</a><span>BEHIND THE MISCHIEF</span></header><main><div class="title"><div>THE OFFICE SUPPLY CABINET</div><h1>Before the jello.</h1><p>Seven office essentials, Dwight on supervision duty, and a walkable Scranton branch. Built in Blender.</p></div><nav><button id="show-assets" class="active">Assets</button><button id="show-preview">Interactive preview</button></nav><section id="assets"><img src="/assets/blender/scranton-studio.png" alt="Actual Blender overview of the connected Scranton office, including reception, sales, private offices, kitchen and annex."/><div class="asset-links">${PROPS.map((s,i)=>`<a href="/assets/blender/${s.id}.glb" download><span>0${i+1}</span><b>${s.id.replaceAll('-',' ')}</b><small>Download GLB ↗</small></a>`).join('')}</div><p class="caption">Actual Blender Cycles render · <a href="https://github.com/itssotsot/TheOffice/releases/download/v1.0.0/scranton-office-v37.blend" download>Download walkable Scranton source</a> · <a href="https://github.com/itssotsot/TheOffice/releases/download/v1.0.0/workstation-reference-v1.blend" download>Download LCD and keyboard source</a> · <a href="https://github.com/itssotsot/TheOffice/releases/download/v1.0.0/workstation-reference-v2.blend" download>Download resized desk</a> · <a href="https://github.com/itssotsot/TheOffice/releases/download/v1.0.0/office-room-v2.blend" download>Download editable office room</a> · <a href="https://github.com/itssotsot/TheOffice/releases/download/v1.0.0/office-props-v2.blend" download>Download original supplies & updated mug</a></p></section><section id="preview" hidden><div class="viewer" id="viewer"></div><div class="viewer-controls">${PROPS.map((s,i)=>`<button data-prop="${i}" class="${i===0?'active':''}">${s.id.replaceAll('-',' ')}</button>`).join('')}</div><p class="caption">Drag to orbit · Scroll to zoom · Walk through the office in the game.</p><button id="bobble-preview" hidden>Give Dwight a bobble</button><p id="viewer-status" role="status">Loading prop…</p></section></main><footer>Made for an exceptionally unproductive afternoon.</footer>`;
const assets=document.querySelector<HTMLElement>('#assets')!,preview=document.querySelector<HTMLElement>('#preview')!,host=document.querySelector<HTMLElement>('#viewer')!;
const render=new THREE.WebGLRenderer({antialias:true});render.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(render.domElement);render.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e5e7dc');const pmrem=new THREE.PMREMGenerator(render),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;pmrem.dispose();room.dispose();
scene.add(new THREE.HemisphereLight('#ffffff','#90997b',3));const light=new THREE.DirectionalLight('white',3);light.position.set(3,5,4);scene.add(light);
const camera=new THREE.PerspectiveCamera(35,1,.1,600);camera.position.set(2.8,3.3,3.5);const controls=new OrbitControls(camera,render.domElement);controls.target.set(0,.25,0);controls.enableDamping=true;controls.maxDistance=1200;controls.minDistance=.5;controls.update();
const loader=new GLTFLoader();let prop:THREE.Object3D|undefined,request=0,bobble:Bobblehead|undefined;
async function addOfficeWorkstation(room:THREE.Object3D){
  const [navigation,models]=await Promise.all([
    fetch('/assets/blender/scranton-navigation.json').then(r=>{if(!r.ok)throw new Error('Navigation unavailable');return r.json();}),
    Promise.all(['desk',...ITEMS.map(s=>s.id),'dwight-bobblehead'].map(id=>loader.loadAsync(`/assets/blender/${id}.glb`))),
  ]);
  const desk=new THREE.Group();desk.name='Dwight workstation';
  if(navigation.workstation){desk.position.fromArray(navigation.workstation.position);desk.rotation.y=navigation.workstation.rotation;desk.scale.setScalar(navigation.workstation.scale??1);}
  desk.add(models[0].scene);
  ITEMS.forEach((spec,i)=>{const item=new THREE.Group();item.position.set(spec.position[0],.045+spec.size[1]*.24,spec.position[1]);item.rotation.y=spec.rotation;item.scale.setScalar(spec.scale);item.add(models[i+1].scene);desk.add(item);});
  const dwight=new Bobblehead();dwight.setModel(models[models.length-1].scene);desk.add(dwight.group);room.add(desk);
}
async function show(i:number){const token=++request;document.querySelector('#viewer-status')!.textContent='Loading prop…';try{const gltf=await loader.loadAsync(`/assets/blender/${PROPS[i].id}.glb`);if(token!==request)return;if(prop)scene.remove(prop);bobble=undefined;prop=gltf.scene;if(PROPS[i].id==='scranton-office'){prepareOfficeMaterials(prop,render);await addOfficeWorkstation(prop);if(token!==request)return;}const officeModel=PROPS[i].id.startsWith('scranton-');light.intensity=officeModel?1.8:3;scene.environmentIntensity=officeModel?.42:1;scene.traverse(o=>{if(o instanceof THREE.HemisphereLight)o.intensity=officeModel?1.05:3;});if(PROPS[i].id==='dwight-bobblehead'){bobble=new Bobblehead();bobble.group.position.set(0,0,0);bobble.group.rotation.y=0;bobble.setModel(prop);prop=bobble.group;}scene.add(prop);prop.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(prop),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const distance=Math.max(size.x,size.y,size.z)*1.55;camera.far=Math.max(500,distance*5);camera.updateProjectionMatrix();controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(distance*.7,distance*.65,distance));if(PROPS[i].id==='office-room'){controls.target.set(0,-.5,-2);camera.position.set(0,12,23);}if(PROPS[i].id==='scranton-office'){prop.traverse(o=>{if(o.name.startsWith('Ceiling'))o.visible=false;});controls.target.set(21,-5,-9);const aspect=host.clientWidth/Math.max(1,host.clientHeight);camera.position.copy(controls.target).add(new THREE.Vector3(-.18,.78,.60).multiplyScalar(365*Math.max(1,1.4/aspect)));camera.far=1600;camera.updateProjectionMatrix();}controls.update();document.querySelector<HTMLButtonElement>('#bobble-preview')!.hidden=!bobble;document.querySelector('#viewer-status')!.textContent=PROPS[i].id.replaceAll('-',' ');document.querySelectorAll('[data-prop]').forEach((b,k)=>b.classList.toggle('active',i===k));}catch{document.querySelector('#viewer-status')!.textContent='Could not load this prop. Reload to try again.';}}
const params=new URLSearchParams(location.search);if(params.get('office')==='1'){document.body.classList.add('office-preview');document.title='Scranton office — interactive model';const back=document.querySelector<HTMLAnchorElement>('header a')!;back.href='https://github.com/itssotsot/TheOffice';back.textContent='← Project source';document.querySelector('header span')!.textContent='SCRANTON / INTERACTIVE MODEL';}const initial=Math.max(0,PROPS.findIndex(p=>p.id===params.get('asset')));void show(initial);document.querySelector<HTMLButtonElement>('#bobble-preview')!.onclick=()=>bobble?.poke();document.querySelectorAll<HTMLButtonElement>('[data-prop]').forEach(b=>b.onclick=()=>void show(Number(b.dataset.prop)));
function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;render.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}
document.querySelector<HTMLButtonElement>('#show-assets')!.onclick=()=>{assets.hidden=false;preview.hidden=true;document.querySelector('#show-assets')!.classList.add('active');document.querySelector('#show-preview')!.classList.remove('active');};
document.querySelector<HTMLButtonElement>('#show-preview')!.onclick=()=>{assets.hidden=true;preview.hidden=false;document.querySelector('#show-preview')!.classList.add('active');document.querySelector('#show-assets')!.classList.remove('active');resize();};window.addEventListener('resize',resize);
if(params.get('preview')==='1')document.querySelector<HTMLButtonElement>('#show-preview')!.click();
let last=performance.now();function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;if(!preview.hidden){bobble?.step(dt);controls.update();render.render(scene,camera);}}requestAnimationFrame(frame);
